# WARNING - Generated by {fusen} from /dev/flat_performance_evaluation.Rmd: do not edit by hand

test_that("multi_sen_spe_dt_out works", {
  expect_true(inherits(multi_sen_spe_dt_out, "function")) 
})
