# WARNING - Generated by {fusen} from dev/flat_concordence.Rmd: do not edit by hand

df <- data.frame(Test1 = c(rep("Positive", 20), rep("Negative", 20)), Test2 = c(rep("Negative", 5), rep("Positive", 5), rep("Negative", 30)), Test3 = c(rep("Positive", 10), rep("Negative", 25), rep("Positive", 5)), MyVariable = sample(1:100, 40))


res<-group_means_concordence(data_var = df, mean_var = "MyVariable", var1 = "Test1", var2 = "Test2", var3 = "Test3")

test_that("cohen_agreement works", {expect_data_frame(res)})
