# WARNING - Generated by {fusen} from /dev/flat_performance_evaluation.Rmd: do not edit by hand

  df <- data.frame(Index = c(rep("Positive", 20), rep("Negative", 20)), Reference = c(rep("Positive", 10), rep("Negative", 30)))
test_that("sen_spe_for_forest works", {
 expect_error( sens_spe_for_forest(
    data_var = df,
    index = 0.8,
    ref = "Reference",
    conf.level = 0.95
  ))
})
