# WARNING - Generated by {fusen} from /dev/flat_concordence.Rmd: do not edit by hand


df <- data.frame(Test1 = c(rep("Positive", 20), rep("Negative", 20)), Test2 = c(rep("Positive", 30), rep("Negative", 10)))
results <- cohen_agreement(data_var = df, var1 = "Test1", var2 = "Test2")

test_that("cohen_agreement works", {expect_data_frame(results)})


