# WARNING - Generated by {fusen} from /dev/flat_performance_evaluation.Rmd: do not edit by hand

test_that("compare_sen_spe works", {
  expect_data_frame(compare_sen_spe(s1 = 0.07, s2 = 0.038, n1 = 374, n2 = 210))
})
