# WARNING - Generated by {fusen} from /dev/flat_performance_evaluation.Rmd: do not edit by hand

test_that("multi_sen_spe_out_forest works", {
  expect_true(inherits(multi_sen_spe_out_forest, "function")) 
})
