# WARNING - Generated by {fusen} from /dev/flat_variable_manipulations.Rmd: do not edit by hand

#' Age groups
#' 
#' Creates a new categorical variable based on age.
#' 
#' @param data.var Data table
#' @param age Variable containing age in years.
#' @param lim1 Age limit for categorization
#' @param lim2 Age limit for categorization
#' @param lim3 Age limit for categorization
#' @param lim4 Age limit for categorization
#' @param lim5 Age limit for categorization
#'
#' @return creates a columns with typical ranges
#' 
#' @import dplyr
#' @export
#' @examples
#' df = data.frame(ID = c(1:20), AGE = round(runif(20, 3, 86)))
#' age_groups(data.var = df, age = "AGE", lim1=5, lim2=11, lim3=18, lim4=45, lim5=60)
#' df = data.frame(ID = c(1:20), AGE = round(runif(20, 3, 25)))
#' age_groups(data.var = df, age = "AGE", lim1=5, lim2=11, lim3=18)
#' 
age_groups <- function(data.var, age, lim1, lim2, lim3=NULL, lim4=NULL, lim5=NULL){
  ifelse(is.null(lim3), 
                 data.var <- data.var %>% mutate(AGE_CATEG = case_when(data.var[,age] < lim1  ~ paste0("<",lim1),
                                              data.var[,age] >= lim1 & data.var[,age]<lim2  ~ paste0(lim1,"-",lim2-1),
                                              data.var[,age] >= lim2  ~ paste0("≥",lim2))), 
                 ifelse(is.null(lim4), data.var <- data.var %>% mutate(AGE_CATEG = case_when(data.var[,age] < lim1  ~ paste0("<",lim1),
                                              data.var[,age] >= lim1 & data.var[,age]<lim2  ~ paste0(lim1,"-",lim2-1),
                                             data.var[,age] >= lim2 & data.var[,age]<lim3  ~ paste0(lim2,"-",lim3-1),
                                             data.var[,age] >= lim2  ~ paste0("≥",lim3))),
                 ifelse(is.null(lim5), data.var <- data.var %>% mutate(AGE_CATEG = case_when(data.var[,age] < lim1  ~ paste0("<",lim1),
                                              data.var[,age] >= lim1 & data.var[,age]<lim2  ~ paste0(lim1,"-",lim2-1),
                                             data.var[,age] >= lim2 & data.var[,age]<lim3  ~ paste0(lim2,"-",lim3-1),
                                             data.var[,age] >= lim3 & data.var[,age]<lim4  ~ paste0(lim3,"-",lim4-1),
                                             data.var[,age] >= lim4  ~ paste0("≥",lim4))),
                                      data.var <- data.var %>% mutate(AGE_CATEG = case_when(data.var[,age] < lim1  ~ paste0("<",lim1),
                                              data.var[,age] >= lim1 & data.var[,age]<lim2  ~ paste0(lim1,"-",lim2-1),
                                             data.var[,age] >= lim2 & data.var[,age]<lim3  ~ paste0(lim2,"-",lim3-1),
                                             data.var[,age] >= lim3 & data.var[,age]<lim4  ~ paste0(lim3,"-",lim4-1),
                                             data.var[,age] >= lim4 & data.var[,age]<lim5  ~ paste0(lim4,"-",lim5-1),
                                             data.var[,age] >= lim5  ~ paste0("≥",lim5))))))

    return(data.var)
}
