# Generated by fusen: do not edit by hand

#' Age groups
#' 
#' Creates a new categorical variable based on age.
#' 
#' @param data.var Data table
#' @param temperature Variable containing age in years.
#'
#' @return
#' 
#' @import dplyr
#' @export
#' @examples
#' df = data.frame(ID = c(1:20), AGE = runif(20, 18, 86))
#' age_groups(data.var = df, age = "AGE")
age_groups <- function(data.var, age ){
    data.var <- data.var %>% mutate(AGE_CATEG = case_when(data.var[,age] < 18  ~ "<18",
                                              data.var[,age] >= 18 & data.var[,age]<30  ~ "18-29",
                                             data.var[,age] >= 30 & data.var[,age]<40  ~ "30-39",
                                             data.var[,age] >= 40 & data.var[,age]<50  ~ "40-49",
                                             data.var[,age] >= 50 & data.var[,age]<60  ~ "50-60",
                                             data.var[,age] >= 60  ~ "≥60"))
    return(data.var)
}
