# WARNING - Generated by {fusen} from dev/flat_variable_manipulations.Rmd: do not edit by hand

#' Age and DOB processing
#' 
#' The function first calculates the age based on the present age variable and if unavailable date of birth and enrollment/consent date, end then runs the age_groups function to divide into different categories.
#' 
#' @param data.var Data table
#' @param age.var Variable containing age in years.
#' @param dob.var Variable containing date of birth
#' @param date.var Variable containing enrolment/consent date 
#' @param lim1 Age limit for categorization
#' @param lim2 Age limit for categorization
#' @param lim3 Age limit for categorization
#' @param lim4 Age limit for categorization
#' @param lim5 Age limit for categorization
#' 
#' @import dplyr
#' @import lubridate
#' 
#' @return Returns the data table with a calculated age column and categorized age column added. 
#' @export
#' @examples
#' library(dplyr)
#' library(lubridate)
#'
#'
#' my_data <- data.frame(
#'   ID = c(1, 2, 3, 4, 5),
#'   age = c(25, NA, 30, NA, NA),
#'   dob = c("1980-01-15", "1995-03-22", "1975-08-10", "1988-11-05", "2000-09-30"),
#'   date_enrollment = c("2023-05-10", "2022-12-01", "2022-02-18", "2023-02-05", "2021-07-20")
#' )
#'
#' # Display the data
#' print(my_data)
#'
#' # Apply the age_dob_process function to the data
#' age_dob_process(data.var=my_data, age.var = "age", dob.var = "dob", date.var = "date_enrollment", lim1 = 30, lim2 = 40)
#'
#'

age_dob_process <-
  function(data.var, age.var, dob.var, date.var, lim1, lim2, lim3 = NULL, lim4 = NULL, lim5 = NULL) {
    data1 <- data.var %>%
    mutate(AGE_CALC = case_when(
      
      !is.na(data.var[,age.var]) ~ data.var[,age.var],
      is.na(data.var[,age.var]) ~ as.numeric(difftime(as.Date(data.var[,date.var]), as.Date(data.var[,dob.var]), unit = "days")) / 365.25
    ))
    
    datareturn <-
      age_groups(
        data.var = data1,
        lim1 = lim1,
        lim2 = lim2,
        lim3 = lim3,
        lim4 = lim4,
        lim5 = lim5,
        age = "AGE_CALC"
      )
    return(datareturn)
  }
