# WARNING - Generated by {fusen} from /dev/flat_performance_evaluation.Rmd: do not edit by hand

#' Confidence Interval Calculator
#' 
#' Calculates the confidence interval of a given proportion with normal approximation.
#' 
#' @param alpha significance level
#' @param proportion the proportion
#' @param n sample size
#'
#' @return
#' 
#' @importFrom checkmate expect_number
#' @importFrom stats qnorm
#' @export
#' @examples
#' CI_Calc(alpha=0.05, proportion=0.62, n= 500)
CI_Calc <- function(alpha, proportion, n){
  alpha_val         <- 1-alpha/2
  z = qnorm(alpha_val)
  ci = z*sqrt((proportion*(1-proportion))/n)
  return(round(ci, digits = 4))
}
