# Generated by fusen: do not edit by hand

#' Cohen agreement
#' 
#' Calculates Cohen's kappa and generates a table including number of positive and negative agreement, as well as positive, negative,  overall percent agreements, and the Kappa value.
#' 
#' @param data_var data table 
#' @param var1 The test with "Positive" and "Negative"results.
#' @param var2 The comparator with "Positive" and "Negative"results.
#'
#' @return Data table
#' 
#' @import checkmate
#' @import dplyr
#' @importFrom irr kappa2
#' @export
#' @examples
#' 
#' df <- data.frame(Test1 = c(rep("Positive", 20), rep("Negative", 20)), Test2 = c(rep("Positive", 30), rep("Negative", 10)))
#' cohen_agreement(data_var = df, var1 = "Test1", var2 = "Test2")
#' 
cohen_agreement <- function(data_var, var1, var2){
  kappa_val      <- format(round(kappa2(data_var[, c(var1, var2)])$value, 2), nsmall = 2)
  All_pos        <- data_var %>% filter_at(vars(c(var1, var2)), all_vars(. == 'Positive')) %>% dplyr::count()
  All_neg        <- data_var %>% filter_at(vars(c(var1, var2)), all_vars(. == 'Negative')) %>% dplyr::count()
  testP_compN    <- data_var %>% filter_at(vars(var1) , all_vars(. == 'Positive')) %>% filter_at(vars(var2) , all_vars(. == 'Negative')) %>% dplyr::count()
  testN_compP    <- data_var %>% filter_at(vars(var1) , all_vars(. == 'Negative')) %>% filter_at(vars(var2) , all_vars(. == 'Positive')) %>% dplyr::count()
  perc_agreement <- format(round(100*(All_pos+All_neg)/(All_pos+All_neg+testP_compN+testN_compP), 1), nsmall = 1)
  PPA            <- as.numeric(format(round(100*(All_pos/(All_pos+testN_compP)), 1), nsmall=1))
  NPA            <- as.numeric(format(round(100*(All_neg/(All_neg+testP_compN)), 1), nsmall=1))
  ci_ppa         <- round(CI_Calc(0.05, PPA/100, as.numeric(All_pos+testN_compP)), 1)
  ci_npa         <- round(CI_Calc(0.05, NPA/100, as.numeric(All_neg+testP_compN)), 1)
  L_PPA          <- PPA - ci_ppa
  U_PPA          <- PPA + ci_ppa
  L_NPA          <- NPA - ci_npa
  U_NPA          <- NPA + ci_npa
  data_return    <- c(`All Positive` = All_pos, `Test(+) Comp(-)` = testP_compN, `Test(-) Comp(+)` = testN_compP,`All Negative` = All_neg,
                      `NPA` = NPA, `Lower bound 95% CI NPA` = L_NPA, `Upper bound 95% CI NPA` = U_NPA,
                      `PPA` = PPA,  `Lower bound 95% CI PPA` = L_PPA, `Upper bound 95% CI PPA` = U_PPA,
                      `Percentage of agreement` = perc_agreement,`Cohen's Kappa` = kappa_val)

  data_return    <- as.data.frame(t(data_return))

  return(data_return)
}
