# WARNING - Generated by {fusen} from dev/flat_concordence.Rmd: do not edit by hand

#' Cohen agreement
#' 
#' Calculates Cohen's kappa and generates a table including number of positive and negative agreement, as well as positive, negative,  overall percent agreements, and the Kappa value.
#' 
#' @param data_var data table 
#' @param var1 The test with "Positive" and "Negative"results.
#' @param var2 The comparator with "Positive" and "Negative"results.
#'
#' @return Data table
#' 
#' @import checkmate
#' @import dplyr
#' @importFrom irr kappa2
#' @export
#' @examples
#'
#' df <- data.frame(Test1 = c(rep("Positive", 20), rep("Negative", 20)), Test2 = c(rep("Positive", 30), rep("Negative", 10)))
#' cohen_agreement(data_var = df, var1 = "Test1", var2 = "Test2")
#'
cohen_agreement <- function(data_var, var1, var2){

  kappa_val      <- format(round(kappa2(data_var[, c(var1, var2)])$value, 2), nsmall = 2)
  All_pos        <- data_var %>% filter_at(vars(c(var1, var2)), all_vars(. == 'Positive')) %>% dplyr::count()
  All_neg        <- data_var %>% filter_at(vars(c(var1, var2)), all_vars(. == 'Negative')) %>% dplyr::count()
  testP_compN    <- data_var %>% filter_at(vars(var1) , all_vars(. == 'Positive')) %>% filter_at(vars(var2) , all_vars(. == 'Negative')) %>% dplyr::count()
  testN_compP    <- data_var %>% filter_at(vars(var1) , all_vars(. == 'Negative')) %>% filter_at(vars(var2) , all_vars(. == 'Positive')) %>% dplyr::count()
  TOT            <- All_pos + All_neg + testP_compN + testN_compP
  perc_agreement <- as.numeric(format(round(100*(All_pos+All_neg)/(TOT), 1), nsmall = 1))
  PPA            <- as.numeric(format(round(100*(All_pos/(All_pos+testN_compP)), 1), nsmall=1))
  NPA            <- as.numeric(format(round(100*(All_neg/(All_neg+testP_compN)), 1), nsmall=1))
  ci_ppa         <- round(CI_Calc(0.05, PPA/100, as.numeric(All_pos+testN_compP))*100, 1)
  ci_npa         <- round(CI_Calc(0.05, NPA/100, as.numeric(All_neg+testP_compN))*100, 1)
  ci_apa         <- round(CI_Calc(0.05, perc_agreement/100, as.numeric(TOT))*100, 1)
  L_PPA          <- round(PPA - ci_ppa,1)
  U_PPA          <- ifelse((PPA + ci_ppa) < 100, round(PPA + ci_ppa,1), 100)
  L_NPA          <- round(NPA - ci_npa,1)
  U_NPA          <- ifelse((NPA + ci_npa) < 100, round(NPA + ci_npa,1), 100)
  L_perc_agree   <- round(perc_agreement - ci_apa,1)
  U_perc_agree   <- ifelse((perc_agreement + ci_apa) < 100, round(perc_agreement + ci_apa,1), 100)
  data_return    <- c(`All Positive` = All_pos, `Test(+) Comp(-)` = testP_compN, `Test(-) Comp(+)` = testN_compP,`All Negative` = All_neg,
                      `NPA` = NPA, `Lower bound 95% CI NPA` = L_NPA, `Upper bound 95% CI NPA` = U_NPA,
                      `PPA` = PPA,  `Lower bound 95% CI PPA` = L_PPA, `Upper bound 95% CI PPA` = U_PPA,
                      `Percentage of agreement` = perc_agreement,`Lower bound 95% CI Overall PA` = L_perc_agree, `Upper bound 95% CI Overall PA` = U_perc_agree,`Cohen's Kappa` = kappa_val)
  
  data_return    <- as.data.frame(t(data_return))
  
  return(data_return)
}
