# Generated by fusen: do not edit by hand

#' composite_reference 
#' 
#' Generates a composite reference based on 3 tests. When any of the tests is positive, subject is classified as positive.
#' Works with 2 or 3 reference tests.
#'
#' @param ref_1 Test1 containing "Positive or "Negative" Results
#' @param ref_2 Test2 containing "Positive or "Negative" Results
#' @param ref_3 Test3 containing "Positive or "Negative" Results
#' @param data_frame  Data table containing the 3 tests
#'
#' @return Data table with composite reference added
#' @export
#' @importFrom plyr rename
#' @import dplyr
#'
#' @examples
#' df <- data.frame(T1 = c(rep("Positive", 10), rep("Negative", 10), rep("Negative", 10)), T2 = c(rep("Positive", 10), rep("Positive", 10), rep("Negative", 10)))
#' composite_reference(ref_1 = "T1", ref_2 = "T2", ref_3 = NULL, data_frame = df)
composite_reference <- function(ref_1, ref_2, ref_3 = NULL, data_frame){
  if (is.null(ref_3)){
    colname <- paste0(ref_1, "_", ref_2)
    data_frame <- data_frame %>% mutate(col = case_when(data_frame[,ref_1] == "Positive" | data_frame[,ref_2] == "Positive"~ "Positive",
                                                                data_frame[,ref_1] == "Negative" & data_frame[,ref_2] == "Negative"~ "Negative"))

  } else {
    #browser()
    colname <- paste0(ref_1, "_", ref_2, "_", ref_3)
    data_frame <- data_frame %>% mutate( col = case_when(data_frame[,ref_1] == "Positive" | data_frame[,ref_2] == "Positive" | data_frame[,ref_3] == "Positive"~ "Positive",
                                                                data_frame[,ref_1] == "Negative" & data_frame[,ref_2] == "Negative" & data_frame[,ref_3] == "Negative"~ "Negative"))
  }
  data_frame <- plyr::rename(data_frame,c("col"= colname))
  return(data_frame)
}

