# WARNING - Generated by {fusen} from dev/flat_composite_reference.Rmd: do not edit by hand

#' composite_for_roc
#' 
#' Define multiple composite references to make an analysis similar to a ROC curve but where diagnostic ability of a binary classifier system is assessed as THE REFERENCE discrimination threshold is varied.
#' 
#' @param ref_1 Reference 1
#' @param ref_2  Reference 2
#' @param test_refs Reference categorized based on multiple thresholds
#' @param data_frame Data table
#'
#' @return Data table containing all possible composite references based on the thresholds applied
#' 
#' @export
composite_for_roc <- function(ref_1, ref_2, test_refs, data_frame){
  composite_ref <- data_frame
  for (i in test_refs){
    composite_ref <- composite_reference(ref_1 = ref_1, ref_2 = ref_2, ref_3 = i, data_frame = composite_ref)
  }
  return(composite_ref)
}
