# WARNING - Generated by {fusen} from dev/flat_concordence.Rmd: do not edit by hand

#' format_colnames
#' 
#' Edits the column names of the table generated by cohen_agreement, to make it more explicit.
#' 
#' @param data_frame the data table generated by cohen_agreement
#' @param test1 Names of the test
#' @param test2 Name of the comparator
#'
#' @return Returns nicely formatted colnames
#' 
#' @export
#' @examples
#'
#' df <- data.frame(Test1 = c(rep("Positive", 20), rep("Negative", 20)), Test2 = c(rep("Positive", 30), rep("Negative", 10)))
#' results <- cohen_agreement(data_var = df, var1 = "Test1", var2 = "Test2")
#' print(results)
#' format_colnames(data_frame = results, test1 = "This Test", test2 = "The Other Test")
format_colnames <- function(data_frame, test1, test2){
  colnames(data_frame) <-
    c(
      "All Positive",
      paste0(test1,"(+) ", test2,"(-)"),
      paste0(test1,"(-) ", test2,"(+)") ,
      "All Negative",
      "NPA",
      "Lower bound 95% CI NPA",
      "Upper bound 95% CI NPA" ,
      "PPA",
      "Lower bound 95% CI PPA",
      "Upper bound 95% CI PPA",
      "Overall PA",
      "Lower bound 95% CI Overall PA",
      "Upper bound 95% CI Overall PA",
      "Cohen's Kappa"
    )
  return(data_frame)
}
