# WARNING - Generated by {fusen} from /dev/flat_performance_evaluation.Rmd: do not edit by hand

#' multi_sen_spe with DT table output
#' 
#' Executes multi_sen_spe function and creates a nicely formatted table output with download options using DT package
#' 
#' @param data_var Data table containing tests results
#' @param list_index A list of index tests with "Negative" and "Positive" results
#' @param ref The reference test with "Negative" and "Positive" results
#' @param conf.level The confidence level, 1-alpha – default 95%
#' @param index_names An optional list containing names of the index tests
#' @param file_name  An optional text containing the name of the file that will be downloaded
#'
#' @return A formatted data table displaying performance characteristics
#' @importFrom DT datatable
#' @export
#' @examples
#' df <- data.frame(Index1 = c(rep("Positive", 20), rep("Negative", 20)), Index2 = c(rep("Positive", 5), rep("Negative", 35)), Index3 = c(rep("Positive", 9), rep("Negative", 31)), Reference = c(rep("Positive", 10), rep("Negative", 30)))
#' 
#' 
#' multi_sen_spe_dt_out(data_var = df, list_index = c("Index1", "Index2", "Index3"), ref = "Reference", conf.level = 0.95, file_name = "ZX001_performance", index_names = c("a", "b", "c"))
multi_sen_spe_dt_out <- function(data_var, list_index, ref, conf.level = 0.95, index_names = NULL, file_name="performance_eval"){
    
  datatable(multi_sen_spe(data_var, list_index = list_index, ref = ref, index_names = index_names, conf.level=conf.level ),
                  extensions = 'Buttons',
                  options = list(dom = 'Blfrtip',
                                 buttons = list(
                                   list(extend = 'copy', filename = file_name),
                                   list(extend = 'csv', filename = file_name),
                                   list(extend = 'excel', filename = file_name),
                                   list(extend = 'pdf', filename = file_name)),
                                 lengthMenu = list(c(10,-1),
                                                   c(10,"All"))))

}
