# WARNING - Generated by {fusen} from /dev/flat_performance_evaluation.Rmd: do not edit by hand

#' multi_sen_spe_forest for forest plots
#' 
#' Calculates and displays sensitivity and specificity with confidence intervals from a data frame for multiple index tests and the reference test. To be used for displaying the result in a table.
#' 
#' @param data_var  Data table containing test results
#' @param list_index A list of index test with "Negative" and "Positive" results
#' @param ref The reference test with "Negative" and "Positive" results
#' @param conf.level The confidence level, 1-alpha – default 95%
#' @param index_names An optional list containing names of the index tests
#'
#' @return A data table with TP/FP/TN/FN, sensitivity, specificity and confidence intervals, to be fed into forestplot function.
#' 
#' @export
#' @examples
#' 
#' df <- data.frame(Index1 = c(rep("Positive", 20), rep("Negative", 20)), Index2 = c(rep("Positive", 5), rep("Negative", 35)), Index3 = c(rep("Positive", 9), rep("Negative", 31)), Reference = c(rep("Positive", 10), rep("Negative", 30)))
#' 
#' multi_sen_spe_forest(data_var = df, list_index = c("Index1", "Index2", "Index3"), ref = "Reference", conf.level = 0.95, index_names = c("ate","FNDH", "DXCb"))
multi_sen_spe_forest <- function(data_var, list_index, ref, conf.level = 0.95, index_names = NULL){
  data_to_forest <- data.frame()
  for (i in list_index){
      df <- sens_spe_for_forest(data_var, i, ref, conf.level = 0.95)
      data_to_forest <- rbind(data_to_forest, df)
  }
  ifelse(
    is.null(index_names),
    data_to_forest$Test <-
      list_index,
    data_to_forest$Test <- index_names
  )
    return(data_to_forest)
}
