# WARNING - Generated by {fusen} from /dev/flat_performance_evaluation.Rmd: do not edit by hand

#' multi_sen_spe with forest plot output
#' 
#' Executes multi_sen_spe function and creates forest plots automatically. 
#' 
#' @param data_var Data table containing tests results
#' @param list_index A list of index tests with "Negative" and "Positive" results
#' @param ref The reference test with "Negative" and "Positive" results
#' @param conf.level The confidence level, 1-alpha – default 95%
#' @param index_names An optional list containing names of the index tests
#' @param labels An optional text for the axis label
#' 
#' @return Interactive forest plots in a list
#' 
#' @export
#' @import ggplot2

#' @import plotly

#' @examples
#' df <- data.frame(Index1 = c(rep("Positive", 20), rep("Negative", 20)), Index2 = c(rep("Positive", 5), rep("Negative", 35)), Index3 = c(rep("Positive", 9), rep("Negative", 31)), Reference = c(rep("Positive", 10), rep("Negative", 30)))
#' plots <- multi_sen_spe_out_forest(data_var = df, list_index = c("Index1", "Index2", "Index3"), ref = "Reference", conf.level = 0.95, labels = "Index Tests", index_names = c("a", "b", "c"))
#' plots[[1]]
#' plots[[2]]
multi_sen_spe_out_forest <- function(data_var, list_index, ref, conf.level = 0.95, index_names = NULL, labels = "Tests"){
  
  perf_forest <- multi_sen_spe_forest(
  data_var = data_var,
  list_index = list_index,
  ref = ref,
  conf.level = conf.level,
  index_names = index_names
)



fp_sen <- ggplot(data=perf_forest, aes(x=Test, y=Sensitivity, ymin=SensLower, ymax=SensUpper)) +
        geom_pointrange() + 
        coord_flip() +
        xlab(labels) + ylab("Sensitivity (95% CI)") +
        theme_classic() +
        scale_y_continuous(limits = c(0, 100),breaks = c(0, 20, 40, 60, 80, 100))+
        geom_point(size = 2, shape = 15)

fp_spe <- ggplot(data=perf_forest, aes(x=Test, y=Specificity, ymin=SpeLower, ymax=SpeUpper)) +
        geom_pointrange() + 
        coord_flip() +
        xlab(labels) + ylab("Specificity (95% CI)") +
        theme_classic() +
        scale_y_continuous(limits = c(0, 100),breaks = c(0, 20, 40, 60, 80, 100))+
        geom_point(size = 2, shape = 15)


forestplots <- list(ggplotly(fp_sen), ggplotly(fp_spe))

return(forestplots)
    
}
