# WARNING - Generated by {fusen} from /dev/flat_performance_evaluation.Rmd: do not edit by hand

#' multi_sen_spe for Table Display
#' 
#' Calculates and displays sensitivity and specificity with confidence intervals from a data frame for multiple index tests and the reference test. To be used for displaying the result in a table.
#' 
#' @param data_var Data table containing tests results
#' @param list_index A list of index tests with "Negative" and "Positive" results
#' @param ref The reference test with "Negative" and "Positive" results
#' @param conf.level The confidence level, 1-alpha – default 95%
#' @param index_names An optional list containing names of the index tests
#'
#' @return A data table with TP/FP/TN/FN, sensitivity, specificity and confidence intervals for all index tests specified in the list
#' 
#' @export
#' @examples
#' library(finddataanalysis)
#' df <- data.frame(Index1 = c(rep("Positive", 20), rep("Negative", 20)), Index2 = c(rep("Positive", 5), rep("Negative", 35)), Index3 = c(rep("Positive", 9), rep("Negative", 31)), Reference = c(rep("Positive", 10), rep("Negative", 30)))
#' 
#' multi_sen_spe(data_var = df, list_index = c("Index1", "Index2", "Index3"), ref = "Reference", conf.level = 0.95, index_names = c("a", "b", "c"))
#' 
#' 
multi_sen_spe <- function(data_var, list_index, ref, conf.level = 0.95, index_names = NULL){
    performance_display <- data.frame()
  for(i in list_index){
    df <- sens_spe(data_var = data_var, index = i, ref = ref, conf.level = conf.level)
    performance_display <- rbind(performance_display, df)
  }
    ifelse(
    is.null(index_names),
    rownames(performance_display) <-
      list_index,
    rownames(performance_display) <- index_names
  )
  return(performance_display)
}
