# Generated by fusen: do not edit by hand

#' Title
#' 
#' Calculates sensitivity and false positivity rate based on the multiple reference columns defined by the thresholds
#' 
#' @param data_var data table
#' @param index index test column containing results: "Positive" or "Negative"
#' @param ref a list containing names of the reference test columns
#' @param conf.level confidence level
#' @param var_name_suffix_cut the suffix based on which the reference test column name to be cut. This will result in suffix + threshold
#'
#' @return
#' 
#' @export
ROC_calculate <- function(data_var, index, ref, conf.level = 0.95, var_name_suffix_cut){
  ROC_df <- data_frame()
  name = c()
  for ( i in ref){
    name <- append(name, strsplit(i, var_name_suffix_cut)[[1]][2])
    sen_spe_df <- sens_spe_for_forest(data_var = data_var, index = index, ref = i, conf.level = 0.95)
    ROC_df <- rbind(ROC_df, sen_spe_df)
  }
ROC_df$Ref_Threshold <-  name
ROC_df$FPR <- 100 - ROC_df$Specificity
return(ROC_df)
}
