# WARNING - Generated by {fusen} from /dev/flat_performance_evaluation.Rmd: do not edit by hand

#' Sensitivity and specificity (Table Display)
#' 
#' Calculate sensitivity and specificity with confidence intervals from a data frame that contains the results of the index and the reference test. 
#' To be used for displaying the result in a table.
#' 
#' @param data_var Data table containing test results
#' @param index The index test with "Negative" and "Positive" results
#' @param ref The reference test with "Negative" and "Positive" results
#' @param conf.level The confidence level, 1-alpha -- default 95%
#'
#' @return A data table with TP/FP/TN/FN, sensitivity, specificity and confidence intervals
#' @import dplyr
#' @import assertthat 
#' @import PropCIs
#' @export
#' @examples
#' df <- data.frame(Index = c(rep("Positive", 5), rep("Negative", 30), rep("Positive", 5)), Reference = c(rep("Positive", 10), rep("Negative", 30)))
#' sens_spe(data_var = df, index = "Index", ref = "Reference", conf.level = 0.95)
sens_spe <- function(data_var, index, ref, conf.level = 0.95){
  #verify that these are column names in characters
  assert_that(is.character(index))
  assert_that(is.character(ref))

  # Calculate number of TP.

table <- sens_spe_for_forest(data_var = data_var, index = index, ref = ref, conf.level = 0.95)

  sens_ci_text <- paste0('[', format(table$SensLower, nsmall = 1), '-', format(table$SensUpper, nsmall = 1), ']')
  spe_ci_text  <- paste0('[', format(table$SpeLower, nsmall = 1), '-', format(table$SpeUpper, nsmall = 1), ']')
  BA_ci_text   <- paste0('[', format(table$BAlower, nsmall = 1), '-', format(table$BAupper, nsmall = 1), ']')
  DOR_ci_text   <- paste0('[', format(table$DORLower, nsmall = 1), '-', format(table$DORUpper, nsmall = 1), ']')


  data_to_return_1	<- c(N = table$N, TP = table$TP, FP = table$FP, FN = table$FN, TN = table$TN, `Sensitivity` = table$Sensitivity, `Sensitivity [95%CI]` = sens_ci_text, `Specificity` = table$Specificity, `Specificity [95%CI]` = spe_ci_text, `Balanced Accuracy` = table$Balanced_Accuracy, `B. Accuracy [95%CI]` = BA_ci_text, `DOR` = table$DOR, `DOR [95%CI]` = DOR_ci_text, PPV = table$PPV, NPV = table$NPV, Accuracy = table$Accuracy )
  names_tp <- names(data_to_return_1)
  data_to_return_1  <- data.frame(t(data_to_return_1))
  colnames(data_to_return_1) <- names_tp
  return(data_to_return_1)
}
