# Generated by fusen: do not edit by hand

#' Sensitivity and specificity (Table Display)
#' 
#' Calculate sensitivity and specificity with confidence intervals from a data frame that contains the results of the index and the reference test. 
#' To be used for displaying the result in a table.
#' 
#' @param data_var Data table containing test results
#' @param index The index test with "Negative" and "Positive" results
#' @param ref The reference test with "Negative" and "Positive" results
#' @param conf.level The confidence level, 1-alpha -- default 95%
#'
#' @return A data table with TP/FP/TN/FN, sensitivity, specificity and confidence intervals
#' @import dplyr
#' @import assertthat 
#' @import PropCIs
#' @export
#' @examples
#' df <- data.frame(Index = c(rep("Positive", 20), rep("Negative", 20)), Reference = c(rep("Positive", 10), rep("Negative", 30)))
#' sens_spe(data_var = df, index = "Index", ref = "Reference", conf.level = 0.95)
sens_spe <- function(data_var, index, ref, conf.level = 0.95){
  #verify that these are column names in characters
  assert_that(is.character(index))
  assert_that(is.character(ref))

  # Calculate number of TP.
  TP	<- nrow(data_var[which(data_var[,index] == "Positive" & data_var[,ref] == "Positive"),])
  FP	<- nrow(data_var[which(data_var[,index] == "Positive" & data_var[,ref] == "Negative"),])
  FN	<- nrow(data_var[which(data_var[,index] == "Negative" & data_var[,ref] == "Positive"),])
  TN	<- nrow(data_var[which(data_var[,index] == "Negative" & data_var[,ref] == "Negative"),])

  sens	<- TP / (TP + FN)
  sens_CI	<- scoreci(x = TP, n  = (TP + FN), conf.level = conf.level)

  spe		<- TN / (TN +FP)
  spe_CI	<- scoreci(x = TN, n  = (TN + FP), conf.level = conf.level)

  BA <- round((sens+spe)/2*100, 1)
  BA_lci <- (  round(sens_CI$conf.int[1]*100, 1) + round(spe_CI$conf.int[1]*100, 1)) /2
  BA_hci <- (round(sens_CI$conf.int[2]*100, 1) + round(spe_CI$conf.int[2]*100, 1))/2

  sens_text    <- paste0(format(round(sens*100, 1), nsmall = 1))
  sens_ci_text <- paste0('[', format(round(sens_CI$conf.int[1]*100, 1), nsmall = 1), '-', format(round(sens_CI$conf.int[2]*100, 1), nsmall = 1), ']')
  spe_text     <- paste0(format(round(spe*100, 1), nsmall = 1))
  spe_ci_text  <- paste0('[', format(round(spe_CI$conf.int[1]*100, 1), nsmall = 1), '-', format(round(spe_CI$conf.int[2]*100, 1), nsmall = 1), ']')
  BA_ci_text   <- paste0('[', format(BA_lci, nsmall = 1), '-', format(BA_hci, nsmall = 1), ']')

  PPV	<- TP / (TP + FP)
  NPV	<- TN / (TN + FN)
  ACC	<- (TP + TN) / (TP + FP + FN + TN)
  N 		<- TP + TN + FP + FN

  data_to_return_1	<- c(N = N, TP = TP, FP = FP, FN = FN, TN = TN, `Sensitivity` = sens_text, `Sensitivity [95%CI]` = sens_ci_text, `Specificity` = spe_text, `Specificity [95%CI]` = spe_ci_text, `Balanced Accuracy` = BA, `B. Accuracy [95%CI]` = BA_ci_text)
  names_tp <- names(data_to_return_1)
  data_to_return_1  <- data.frame(t(data_to_return_1))
  colnames(data_to_return_1) <- names_tp
  return(data_to_return_1)
}
