# Generated by fusen: do not edit by hand

#' Sensitivity and specificity (for forest plots)
#' 
#' Calculate sensitivity and specificity with confidence intervals from a data frame that contains the results of the index and the reference test. 
#' To be used for displaying the result in a forest plot.
#' 
#' @param data_var Data table containing test results
#' @param index The index test with "Negative" and "Positive" results
#' @param ref The reference test with "Negative" and "Positive" results
#' @param conf.level The confidence level, 1-alpha -- default 95%
#'
#' @return A data table with TP/FP/TN/FN, sensitivity, specificity and confidence intervals
#' @import dplyr
#' @import assertthat 
#' @import PropCIs
#' 
#' @export
#' @examples
#' library(forestplot)
#' df <- data.frame(Index = c(rep("Positive", 20), rep("Negative", 20)), Reference = c(rep("Positive", 30), rep("Negative", 10)))
#' forest_data <- cbind(Test = "Index", sens_spe_for_forest(data_var = df, index = "Index", ref = "Reference", conf.level = 0.95))
#' forest_data %>% forestplot(mean = Sensitivity, 
#'                           lower = SensLower, 
#'                           upper = SensUpper, 
#'                           labeltext = Test,
#'                           title = "Sensitivity",
#'                           zero = NA,
#'                           xticks = c( 0, 20, 40, 60, 80, 100),
#'                           txt_gp = fpTxtGp(ticks=gpar(cex=1)),
#'                           boxsize = .1
#'                           )
sens_spe_for_forest <- function(data_var, index, ref, conf.level = 0.95){
  #verify that these are column names in characters
  assert_that(is.character(index))
  assert_that(is.character(ref))

  # Calculate number of TP.
  TP	<- nrow(data_var[which(data_var[,index] == "Positive" & data_var[,ref] == "Positive"),])
  FP	<- nrow(data_var[which(data_var[,index] == "Positive" & data_var[,ref] == "Negative"),])
  FN	<- nrow(data_var[which(data_var[,index] == "Negative" & data_var[,ref] == "Positive"),])
  TN	<- nrow(data_var[which(data_var[,index] == "Negative" & data_var[,ref] == "Negative"),])

  sens	<- TP / (TP + FN)
  sens_CI	<- scoreci(x = TP, n  = (TP + FN), conf.level = conf.level)

  spe		<- TN / (TN +FP)
  spe_CI	<- scoreci(x = TN, n  = (TN + FP), conf.level = conf.level)

  BA <- round((sens+spe)/2*100, 1)
  BA_lci <- (round(sens_CI$conf.int[1]*100, 1) + round(spe_CI$conf.int[1]*100, 1))/2
  BA_hci <- (round(sens_CI$conf.int[2]*100, 1) + round(spe_CI$conf.int[2]*100, 1))/2

  sens_text    <- paste0(format(round(sens*100, 1), nsmall = 1))
  sens_ci_text <- paste0('[', format(round(sens_CI$conf.int[1]*100, 1), nsmall = 1), '-', format(round(sens_CI$conf.int[2]*100, 1), nsmall = 1), ']')
  spe_text     <- paste0(format(round(spe*100, 1), nsmall = 1))
  spe_ci_text  <- paste0('[', format(round(spe_CI$conf.int[1]*100, 1), nsmall = 1), '-', format(round(spe_CI$conf.int[2]*100, 1), nsmall = 1), ']')


  PPV	<- TP / (TP + FP)
  NPV	<- TN / (TN + FN)
  ACC	<- (TP + TN) / (TP + FP + FN + TN)
  N 		<- TP + TN + FP + FN

  data_to_return_1	<- data.frame(Sensitivity = (sens)*100, Specificity = (spe)*100,
                                 SensLower = (sens_CI$conf.int[1])*100,
                                 SensUpper = (sens_CI$conf.int[2])*100,
                                 SpeLower = (spe_CI$conf.int[1])*100,
                                 SpeUpper = (spe_CI$conf.int[2])*100,
                                 Balanced_Accuracy = BA,
                                 BAlower = BA_lci,
                                 BAupper = BA_hci)
  return(data_to_return_1)
}




