# WARNING - Generated by {fusen} from /dev/flat_variable_manipulations.Rmd: do not edit by hand

#' Regroup axillary temperature values
#' 
#' Creates a new categorical variable based on the body temperature.
#' 
#' @param data.var Data table
#' @param temperature Variable containing body temperature in Celsius
#'
#' @return Creates a new column frame with body temperature ranges
#' 
#' @import dplyr
#' @export
#' @examples
#' 
#' df = data.frame(ID = c(1:20), Temperature = runif(20, 36, 42))
#' temperature_groups(data.var = df, temperature = "Temperature")
temperature_groups <- function(data.var, temperature ){
    data.var <- data.var %>% mutate(TEMP_CATEG = case_when(data.var[,temperature] < 36  ~ "<36",
                                              data.var[,temperature] >= 36 & data.var[,temperature]<37  ~ "36-36.9",
                                             data.var[,temperature] >= 37 & data.var[,temperature]<38  ~ "37-37.9",
                                             data.var[,temperature] >= 38 & data.var[,temperature]<39  ~ "38-38.9",
                                             data.var[,temperature] >= 30  ~ "≥39"))
    return(data.var)
}
